# Keep Room entities — field names accessed via KSP-generated code
-keep class com.example.models.** { *; }

# kotlinx.serialization — required for Supabase AddressRow decoding
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt
-keep,includedescriptorclasses class com.example.**$$serializer { *; }
-keepclassmembers class com.example.** {
    *** Companion;
}
-keepclasseswithmembers class com.example.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep Moshi JsonClass adapters generated by KSP
-keep @com.squareup.moshi.JsonClass class * { *; }

# Retrofit & OkHttp
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }

# Ktor (used by Supabase SDK)
-dontwarn io.ktor.**
-keep class io.ktor.** { *; }
-keep class io.github.jan.supabase.** { *; }

# Coil
-dontwarn coil.**

# WebView JavaScript interface — keep annotated methods from obfuscation
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# Preserve stack traces in crash reports
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
