# Keep Room entities — field names are accessed via KSP-generated code
-keep class com.example.models.** { *; }

# Keep Moshi JsonClass adapters generated by KSP
-keep @com.squareup.moshi.JsonClass class * { *; }

# Retrofit & OkHttp
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }

# Coil
-dontwarn coil.**

# Preserve stack traces in crash reports
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Keep WebView JavaScript interface methods (used in AddressDetailScreen)
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
